# pruebas para API de pacientes
@url = http://localhost:3000

### Login
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "pepe@example.com",
    "password": "hola1234"
}

###
@token = {{login.response.body.token}}

### Consultar pacientes
GET {{url}}/pacientes
Authorization: Bearer {{token}}

### Consultar paciente por ID
GET {{url}}/pacientes/1
Authorization: Bearer {{token}}

### Crear paciente
POST {{url}}/pacientes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Pérez",
    "dni": "30111222",
    "fecha_nacimiento": "1990-05-12",
    "obra_social": "OSDE"
}

### Modificar paciente
PUT {{url}}/pacientes/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Pérez Modificado",
    "dni": "30111222",
    "fecha_nacimiento": "1990-05-12",
    "obra_social": "Swiss Medical"
}

### Eliminar paciente
DELETE {{url}}/pacientes/1
Authorization: Bearer {{token}}
