# pruebas para API de usuarios
@url = http://localhost:3000

### Crear usuario (registro)
# Este paso hay que hacerlo una vez para registrar el primer usuario (admin, por ejemplo) 
POST {{url}}/usuarios
Content-Type: application/json

{
    "nombre": "Admin",
    "email": "admin@mail.com",
    "contraseña": "hola1234"
}

### Login
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "hola1234"
}

###
@token = {{login.response.body.token}}

### Consultar usuarios
GET {{url}}/usuarios
Authorization: Bearer {{token}}

### Consultar usuario por ID
GET {{url}}/usuarios/1
Authorization: Bearer {{token}}

### Crear usuario (desde sesión autenticada)
POST {{url}}/usuarios
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "Carlos",
    "email": "carlos@example.com",
    "contraseña": "hola1234"
}

### Modificar usuario
PUT {{url}}/usuarios/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "Carlos Modificado",
    "email": "carlosmod@example.com"
}

### Eliminar usuario
DELETE {{url}}/usuarios/1
Authorization: Bearer {{token}}
